FROM gcr.io/distroless/java@sha256:51d2d3ceb469c7963a415a4cd37888ff6dec6f048e95b882a2755b91192cd392
ENV QUARKUS_LAUNCH_DEVMODE=true
ENV JAVA_TOOL_OPTIONS='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000'
COPY --chown=nonroot:nonroot target/emptydir /app
WORKDIR /app
COPY --chown=nonroot:nonroot target/quarkus-app/quarkus ./quarkus
COPY --chown=nonroot:nonroot target/quarkus-app/lib ./lib
COPY --chown=nonroot:nonroot target/quarkus-app/quarkus-app-dependencies.txt ./
COPY --chown=nonroot:nonroot target/quarkus-app/app ./app
COPY --chown=nonroot:nonroot target/quarkus-app/*.jar ./
ENTRYPOINT [ \
  "java", \
  "-Dquarkus.http.host=0.0.0.0", \
  "-jar", \
  "quarkus-run.jar" \
]