apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-settings
  labels:
    app: quarkus-devmode
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-workspace
  labels:
    app: quarkus-devmode
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi